[package]
name = "verglas-catalog-authz"
version = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
rust-version = { workspace = true }
repository = { workspace = true }
license = "FSL-1.1-ALv2"

description = "Verglas authorization adapter for Catalog"

[lib]

[features]
open-api = ["dep:utoipa", "verglas-catalog-core/open-api"]

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
axum = { workspace = true }
figment = { workspace = true }
futures = { workspace = true }
jsonwebtoken = { workspace = true }
verglas-catalog-core = { path = "../verglas-catalog-core", default-features = false }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["net"] }
tracing = { workspace = true }
utoipa = { workspace = true, optional = true }

[dev-dependencies]
verglas-catalog-core = { path = "../verglas-catalog-core", features = ["test-utils"] }
tempfile = { workspace = true }
tower = { workspace = true }
