[package]
name = "lakekeeper-storage-verglas"
version = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }
license = "FSL-1.1-ALv2"
description = "CRaft-backed authoritative catalog storage for Lakekeeper"

[dependencies]
async-trait = { workspace = true }
chrono = { workspace = true }
lakekeeper = { path = "../lakekeeper" }
lakekeeper-io = { path = "../io" }
verglas-catalog = { path = "../../../verglas-catalog" }
verglas-consensus = { path = "../../../verglas-consensus" }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
uuid = { workspace = true }
