[package]
name = "verglas-kv"
description = "Tenant-scoped RAM-accelerated, NVMe-persistent key/value storage"
version.workspace = true
edition.workspace = true
repository.workspace = true
homepage.workspace = true
publish.workspace = true

[dependencies]
arc-swap = "1.7.1"
bytes.workspace = true
crc32c.workspace = true
hex.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true

[dev-dependencies]
tempfile.workspace = true
tokio.workspace = true

[lints]
workspace = true
