import type { ProductAnalyticsRecord } from "./analytics";

// Custom environment variable declarations that augment the auto-generated Cloudflare.Env.
// (worker-configuration.d.ts is auto-generated by `wrangler types` and should not be edited.)

declare global {
  namespace Cloudflare {
    interface Env {
      // Deployment-wide admin usernames.
      ADMINS?: string[];

      // Blueprint storage bindings.
      BLUEPRINTS: KVNamespace;             // Workers KV for blueprint metadata lookup
      BLUEPRINT_CONTENT: R2Bucket;         // R2 bucket for blueprint code snapshots

      // User avatar storage.
      AVATARS: KVNamespace;                // Workers KV for user avatar images

      // Note: gatekeeper service bindings (GATEKEEPER_*) are intentionally NOT declared here. Core
      // discovers them generically by scanning env for the GATEKEEPER_ prefix (buildGatekeeperVendorMap)
      // and never references a specific gatekeeper by name, so naming one here would be wrong.

      // Optional product analytics stream. Deployments can bind this to a
      // structured Cloudflare Pipelines stream; local/dev configs omit it and analytics no-op.
      PRODUCT_ANALYTICS?: import("cloudflare:pipelines").Pipeline<ProductAnalyticsRecord>;

      // Optional browser error pipeline. Both bindings must be present before reports dispatch.
      FRONTEND_ERROR_REPORTER?: Service<
        import("@verglas/backend-utils/error-reporting").ErrorReporter
      >;
      FRONTEND_ERROR_RATE_LIMITER?: RateLimit;

      // Browser Run binding used to render Workspace exports. Optional for self-hosted deployments.
      BROWSER?: BrowserRun;

      // ---------------------------------------------------------------------------------------------
      // Optional sign-in via authentication gatekeepers. OAuth app credentials live on the
      // gatekeeper Workers, not here.
      // ---------------------------------------------------------------------------------------------

      // Cloudflare Access configuration. When CF_ACCESS_AUD is set, the deployment authenticates via
      // Cloudflare Access (SSO). (Also referenced via a local Env extension in server.ts.)
      CF_ACCESS_AUD?: string;   // audience
      CF_ACCESS_ISS?: string;   // team URL, e.g. https://<team>.cloudflareaccess.com

      // Comma-separated allowlist of gatekeeper vendor ids permitted to drive sign-in (e.g.
      // "google,github,cloudflare"). A listed gatekeeper must also advertise providesAuth. Empty =
      // no gatekeeper sign-in (password / CF Access only).
      AUTH_GATEKEEPERS?: string;

      // Set to "true" to disable username/password login + signup (gatekeeper sign-in only). Only
      // takes effect when at least one auth gatekeeper is allowlisted (otherwise password auth stays
      // on to avoid locking everyone out).
      DISABLE_PASSWORD_AUTH?: string;

      // Public base URL of the deployment.
      PUBLIC_BASE_URL?: string;


      // Local Verglas worker control plane used by generated Sources.
      VERGLAS_ADMIN_URL?: string;
      VERGLAS_SCHEDULER_URL?: string;
      VERGLAS_SCHEDULER_CONTROL_TOKEN?: string;

      // Trusted local Docker runtime manager used to discover and configure Vessels.
      VERGLAS_CONTAINER_RUNTIME_URL?: string;
      VERGLAS_CONTAINER_RUNTIME_TOKEN?: string;

      // Data-plane capability passed only to generated Integration runtime containers.
      VERGLAS_DATA_ENDPOINT?: string;
      VERGLAS_DATA_TOKEN?: string;
      VERGLAS_INTEGRATION_RUNTIME_IMAGE?: string;

      // Mandatory tenant authorization service. The service token remains backend-only.
      VERGLAS_ACCESS_URI?: string;
      VERGLAS_ACCESS_SERVICE_TOKEN?: string;
      VERGLAS_TENANT_ID?: string;
      // Explicit OSS-only bootstrap: every local account owns the local tenant.
      VERGLAS_LOCAL_OWNER_BOOTSTRAP?: string;

      // Native coding-agent CLI adapter. The bearer token is backend-only.
      LOCAL_MODEL_RUNTIME_URL?: string;
      LOCAL_MODEL_RUNTIME_TOKEN?: string;

    }
  }
}
