name: Security audit

permissions:
  contents: read # Needed to checkout code
  security-events: write # Needed for security reporting

concurrency:
  group: ${{ github.repository }}-${{ github.head_ref || github.sha }}-${{ github.workflow }}
  cancel-in-progress: true

on:
  push:
    paths:
      - "**/Cargo.toml"
      - "**/Cargo.lock"

  pull_request:
    paths:
      - "**/Cargo.toml"
      - "**/Cargo.lock"

jobs:
  security_audit:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          persist-credentials: false
      - name: Install cargo-audit
        run: cargo install cargo-audit --force
      - name: Run audit check
        run: cargo audit

  cargo-deny:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          persist-credentials: false
      - uses: EmbarkStudios/cargo-deny-action@bb137d7af7e4fb67e5f82a49c4fce4fad40782fe # v2.0.20
        with:
          command: check -s --hide-inclusion-graph
