// Generated by verglas-vessel-contract. Do not edit.

export type ConfigurationFieldType = "text" | "secret" | "url" | "number" | "boolean";

export type ConfigurationField = { 
/**
 * Environment-style identifier exposed to the Integration process.
 */
name: string, 
/**
 * Human-readable form label.
 */
label: string, 
/**
 * Input and storage behavior.
 */
type: ConfigurationFieldType, 
/**
 * Whether the Integration may start without a value.
 */
required: boolean, 
/**
 * Optional non-secret initial value.
 */
default?: unknown, 
/**
 * Concise field-level setup help.
 */
help?: string, 
/**
 * Non-sensitive example shown when the field is empty.
 */
placeholder?: string, };

export type ConfigurationStep = { 
/**
 * Short action-oriented heading.
 */
title: string, 
/**
 * Instructions the user can follow without outside context.
 */
description: string, 
/**
 * Optional HTTPS documentation or provider-console link.
 */
url?: string, };

export type IntegrationConfiguration = { 
/**
 * Values the user must or may configure at runtime.
 */
fields: Array<ConfigurationField>, 
/**
 * Ordered provider setup guidance displayed alongside the fields.
 */
setup: Array<ConfigurationStep>, };

export type IntegrationComponent = { 
/**
 * Name used by grants and the reflected Verglas SDK namespace.
 */
name: string, 
/**
 * Independent source version pinned by the containing Vessel release.
 */
version: string, 
/**
 * Relative directory containing the component project.
 */
project: string, 
/**
 * Configuration UI and credential requirements owned by this Integration.
 */
config: IntegrationConfiguration, };

export type EventTrigger = { 
/**
 * Exact CloudEvents `type` value.
 */
event: string, };

export type CronTrigger = { 
/**
 * Five-field UTC cron expression.
 */
cron: string, };

export type TableTrigger = { 
/**
 * Fully qualified table name to observe.
 */
table: string, };

export type WebhookTrigger = { 
/**
 * Absolute path exposed through authenticated Vessel ingress.
 */
webhook: string, };

export type WorkerTrigger = EventTrigger | CronTrigger | TableTrigger | WebhookTrigger;

export type ReadGrant = { 
/**
 * Fully qualified resource name.
 */
read: string, };

export type WriteGrant = { 
/**
 * Fully qualified resource name.
 */
write: string, };

export type DataGrant = ReadGrant | WriteGrant;

export type ComponentGrants = { 
/**
 * Table read and write grants.
 */
tables: Array<DataGrant>, 
/**
 * Vector-index read and write grants.
 */
vectors: Array<DataGrant>, 
/**
 * Graph read and write grants.
 */
graphs: Array<DataGrant>, 
/**
 * Integration API components exposed through the reflected SDK.
 */
integrations: Array<string>, };

export type WorkerComponent = { 
/**
 * Stable Worker definition name.
 */
name: string, 
/**
 * Independent source version pinned by the containing Vessel release.
 */
version: string, 
/**
 * Relative directory containing the Worker project.
 */
project: string, 
/**
 * Events that create Jobs from this Worker definition; empty means manual only.
 */
triggers: Array<WorkerTrigger>, 
/**
 * Lakehouse and Integration capabilities granted to each derived Job.
 */
grants: ComponentGrants, };

export type InterfaceComponent = { 
/**
 * Stable application component name.
 */
name: string, 
/**
 * Independent source version pinned by the containing Vessel release.
 */
version: string, 
/**
 * Relative directory containing the full-stack Interface project.
 */
project: string, 
/**
 * Private HTTP port exposed to the local preview proxy.
 */
port: number, 
/**
 * Lakehouse and Integration capabilities granted to the Interface.
 */
grants: ComponentGrants, };

export type VesselManifest = { 
/**
 * Contract API version. Must be `verglas.io/v1alpha1`.
 */
apiVersion: string, 
/**
 * Manifest kind. Must be `Vessel`.
 */
kind: string, 
/**
 * Stable Vessel name.
 */
name: string, 
/**
 * Immutable source release version of this composition.
 */
version: string, 
/**
 * External API components available to Workers and the Interface.
 */
integrations: Array<IntegrationComponent>, 
/**
 * Data and agentic operations materialized as Jobs at runtime.
 */
workers: Array<WorkerComponent>, 
/**
 * The Vessel's sole graphical application component.
 */
interface: InterfaceComponent, };

/** Parse and validate a Vessel YAML document. */
export declare function parseManifest(yaml: string): VesselManifest;
