/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ApplicationsRouteImport } from './routes/applications'
import { Route as BlueprintsRouteImport } from './routes/blueprints'
import { Route as ContextRouteImport } from './routes/context'
import { Route as DataRouteImport } from './routes/data'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as OutputsRouteImport } from './routes/outputs'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ProvidersRouteImport } from './routes/providers'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as WorkflowsRouteImport } from './routes/workflows'
import { Route as WorkspacesRouteImport } from './routes/workspaces'
import { Route as BlueprintIdRouteImport } from './routes/blueprint.$id'
import { Route as WorkspaceIdRouteImport } from './routes/workspace.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsRoute = ApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const BlueprintsRoute = BlueprintsRouteImport.update({
  id: '/blueprints',
  path: '/blueprints',
  getParentRoute: () => rootRouteImport,
} as any)
const ContextRoute = ContextRouteImport.update({
  id: '/context',
  path: '/context',
  getParentRoute: () => rootRouteImport,
} as any)
const DataRoute = DataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const OutputsRoute = OutputsRouteImport.update({
  id: '/outputs',
  path: '/outputs',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvidersRoute = ProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsRoute = WorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspacesRoute = WorkspacesRouteImport.update({
  id: '/workspaces',
  path: '/workspaces',
  getParentRoute: () => rootRouteImport,
} as any)
const BlueprintIdRoute = BlueprintIdRouteImport.update({
  id: '/blueprint/$id',
  path: '/blueprint/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceIdRoute = WorkspaceIdRouteImport.update({
  id: '/workspace/$id',
  path: '/workspace/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/applications': typeof ApplicationsRoute
  '/blueprints': typeof BlueprintsRoute
  '/context': typeof ContextRoute
  '/data': typeof DataRoute
  '/explore': typeof ExploreRoute
  '/integrations': typeof IntegrationsRoute
  '/outputs': typeof OutputsRoute
  '/profile': typeof ProfileRoute
  '/providers': typeof ProvidersRoute
  '/signup': typeof SignupRoute
  '/workflows': typeof WorkflowsRoute
  '/workspaces': typeof WorkspacesRoute
  '/blueprint/$id': typeof BlueprintIdRoute
  '/workspace/$id': typeof WorkspaceIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/applications': typeof ApplicationsRoute
  '/blueprints': typeof BlueprintsRoute
  '/context': typeof ContextRoute
  '/data': typeof DataRoute
  '/explore': typeof ExploreRoute
  '/integrations': typeof IntegrationsRoute
  '/outputs': typeof OutputsRoute
  '/profile': typeof ProfileRoute
  '/providers': typeof ProvidersRoute
  '/signup': typeof SignupRoute
  '/workflows': typeof WorkflowsRoute
  '/workspaces': typeof WorkspacesRoute
  '/blueprint/$id': typeof BlueprintIdRoute
  '/workspace/$id': typeof WorkspaceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/applications': typeof ApplicationsRoute
  '/blueprints': typeof BlueprintsRoute
  '/context': typeof ContextRoute
  '/data': typeof DataRoute
  '/explore': typeof ExploreRoute
  '/integrations': typeof IntegrationsRoute
  '/outputs': typeof OutputsRoute
  '/profile': typeof ProfileRoute
  '/providers': typeof ProvidersRoute
  '/signup': typeof SignupRoute
  '/workflows': typeof WorkflowsRoute
  '/workspaces': typeof WorkspacesRoute
  '/blueprint/$id': typeof BlueprintIdRoute
  '/workspace/$id': typeof WorkspaceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/applications'
    | '/blueprints'
    | '/context'
    | '/data'
    | '/explore'
    | '/integrations'
    | '/outputs'
    | '/profile'
    | '/providers'
    | '/signup'
    | '/workflows'
    | '/workspaces'
    | '/blueprint/$id'
    | '/workspace/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/applications'
    | '/blueprints'
    | '/context'
    | '/data'
    | '/explore'
    | '/integrations'
    | '/outputs'
    | '/profile'
    | '/providers'
    | '/signup'
    | '/workflows'
    | '/workspaces'
    | '/blueprint/$id'
    | '/workspace/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/applications'
    | '/blueprints'
    | '/context'
    | '/data'
    | '/explore'
    | '/integrations'
    | '/outputs'
    | '/profile'
    | '/providers'
    | '/signup'
    | '/workflows'
    | '/workspaces'
    | '/blueprint/$id'
    | '/workspace/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ApplicationsRoute: typeof ApplicationsRoute
  BlueprintsRoute: typeof BlueprintsRoute
  ContextRoute: typeof ContextRoute
  DataRoute: typeof DataRoute
  ExploreRoute: typeof ExploreRoute
  IntegrationsRoute: typeof IntegrationsRoute
  OutputsRoute: typeof OutputsRoute
  ProfileRoute: typeof ProfileRoute
  ProvidersRoute: typeof ProvidersRoute
  SignupRoute: typeof SignupRoute
  WorkflowsRoute: typeof WorkflowsRoute
  WorkspacesRoute: typeof WorkspacesRoute
  BlueprintIdRoute: typeof BlueprintIdRoute
  WorkspaceIdRoute: typeof WorkspaceIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications': {
      id: '/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof ApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blueprints': {
      id: '/blueprints'
      path: '/blueprints'
      fullPath: '/blueprints'
      preLoaderRoute: typeof BlueprintsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/context': {
      id: '/context'
      path: '/context'
      fullPath: '/context'
      preLoaderRoute: typeof ContextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data': {
      id: '/data'
      path: '/data'
      fullPath: '/data'
      preLoaderRoute: typeof DataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outputs': {
      id: '/outputs'
      path: '/outputs'
      fullPath: '/outputs'
      preLoaderRoute: typeof OutputsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/providers': {
      id: '/providers'
      path: '/providers'
      fullPath: '/providers'
      preLoaderRoute: typeof ProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows': {
      id: '/workflows'
      path: '/workflows'
      fullPath: '/workflows'
      preLoaderRoute: typeof WorkflowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspaces': {
      id: '/workspaces'
      path: '/workspaces'
      fullPath: '/workspaces'
      preLoaderRoute: typeof WorkspacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blueprint/$id': {
      id: '/blueprint/$id'
      path: '/blueprint/$id'
      fullPath: '/blueprint/$id'
      preLoaderRoute: typeof BlueprintIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/$id': {
      id: '/workspace/$id'
      path: '/workspace/$id'
      fullPath: '/workspace/$id'
      preLoaderRoute: typeof WorkspaceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ApplicationsRoute: ApplicationsRoute,
  BlueprintsRoute: BlueprintsRoute,
  ContextRoute: ContextRoute,
  DataRoute: DataRoute,
  ExploreRoute: ExploreRoute,
  IntegrationsRoute: IntegrationsRoute,
  OutputsRoute: OutputsRoute,
  ProfileRoute: ProfileRoute,
  ProvidersRoute: ProvidersRoute,
  SignupRoute: SignupRoute,
  WorkflowsRoute: WorkflowsRoute,
  WorkspacesRoute: WorkspacesRoute,
  BlueprintIdRoute: BlueprintIdRoute,
  WorkspaceIdRoute: WorkspaceIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
