[package]
name = "lakekeeper-authz-verglas"
version = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
rust-version = { workspace = true }
repository = { workspace = true }
license = "FSL-1.1-ALv2"

description = "Verglas authorization adapter for Lakekeeper"

[lib]

[features]
open-api = ["dep:utoipa", "lakekeeper/open-api"]

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
axum = { workspace = true }
figment = { workspace = true }
futures = { workspace = true }
lakekeeper = { path = "../lakekeeper", default-features = false }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["fs", "net"] }
tracing = { workspace = true }
url = { workspace = true }
urlencoding = { workspace = true }
utoipa = { workspace = true, optional = true }

[dev-dependencies]
lakekeeper = { path = "../lakekeeper", features = ["test-utils"] }
tempfile = { workspace = true }
tower = { workspace = true }
