[package]
name = "verglas"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[workspace]

[profile.release]
lto = true
strip = true

[dependencies]
duckdb = { version = "~1.10505.0", features = ["loadable-extension", "vtab-arrow"] }
arrow = "58"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
ureq = { version = "3", features = ["json"] }
http = "1"
url = "2"
