// Generated by verglas-microvm-contract. Do not edit.

export type TenantNetwork = "vxlan";

export type NetworkProtocol = "tcp" | "http";

export type Tenant = { 
/**
 * Stable tenant runtime name.
 */
name: string, 
/**
 * Tenant network implementation.
 */
network: TenantNetwork, };

export type Ingress = { 
/**
 * Component receiving platform traffic.
 */
component: string, 
/**
 * Named port on the ingress component.
 */
port: string, };

export type Runtime = { 
/**
 * Digest-pinned OCI image reference.
 */
image: string, };

export type Cluster = { 
/**
 * Number of stable ordinal members in the cluster.
 */
members: number, };

export type Resources = { 
/**
 * Number of virtual CPUs.
 */
vcpus: number, 
/**
 * Memory allocation in mebibytes.
 */
memoryMiB: number, };

export type NetworkPort = { 
/**
 * Stable port name used by health and ingress references.
 */
name: string, 
/**
 * TCP port number.
 */
port: number, 
/**
 * Protocol served on this port.
 */
protocol: NetworkProtocol, };

export type ComponentNetwork = { 
/**
 * Ports addressable by dependencies or stack ingress.
 */
ports: Array<NetworkPort>, };

export type Health = { 
/**
 * Named port that must accept traffic.
 */
port: string, 
/**
 * Optional HTTP readiness path.
 */
path?: string, };

export type Component = { 
/**
 * Unique name used for dependency and network resolution.
 */
name: string, 
/**
 * Bootable runtime image.
 */
runtime: Runtime, 
/**
 * Process and arguments started inside the microVM.
 */
exec: Array<string>, 
/**
 * Optional fixed-size quorum cluster.
 */
cluster?: Cluster, 
/**
 * Requested microVM compute resources.
 */
resources: Resources, 
/**
 * Optional named ports provided inside the tenant network.
 */
network?: ComponentNetwork, 
/**
 * Optional readiness condition.
 */
health?: Health, 
/**
 * Components that must be healthy before this component starts.
 */
dependsOn?: Array<string>, };

export type MicroVmStack = { 
/**
 * Contract API version. Must be `verglas.io/v1alpha1`.
 */
apiVersion: string, 
/**
 * Manifest kind. Must be `MicroVMStack`.
 */
kind: string, 
/**
 * Tenant identity and isolation network.
 */
tenant: Tenant, 
/**
 * The sole platform-callable entry point for a dormant stack.
 */
ingress: Ingress, 
/**
 * Desired microVM components and their dependency graph.
 */
components: Array<Component>, };

/** Parse and validate a MicroVMStack YAML document. */
export declare function parseManifest(yaml: string): MicroVmStack;
